[package]
name = "interprocess"
version = "1.1.0"
authors = ["Kotauskas <v.toncharov@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/interprocess"
repository = "https://github.com/kotauskas/interprocess"

description = "Interprocess communication toolkit"
categories = ["os", "os::unix-apis", "os::windows-apis", "asynchronous"]
keywords = ["ipc", "shared_memory", "pipe", "unix_domain_socket"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = {version = "0.2", features = ["extra_traits"]}
thiserror = "1.0"
spinning = "0.1"
intmap = "0.7"
lazy_static = "1.4"
blocking = {version = "1.0", optional = true}
futures = {version = "0.3", optional = true}
cfg-if = "1.0"

[dev_dependencies]
tokio = {version = "1.0", features = ["rt", "macros", "rt-multi-thread"]}

[target.'cfg(windows)'.dependencies]
winapi = {version = "0.3", features = ["std", "winbase", "winerror", "processthreadsapi", "fileapi", "handleapi", "namedpipeapi"]}

[features]
default = []
nonblocking = ["blocking", "futures"]
doc_cfg = []

[[example]]
name = "async_local_socket_client"
required-features = ["nonblocking"]

[[example]]
name = "async_local_socket_server"
required-features = ["nonblocking"]

[package.metadata.docs.rs]
features = ["doc_cfg"]
