[package]
name = "interprocess"
version = "1.1.1"
authors = ["Kotauskas <v.toncharov@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/interprocess"
repository = "https://github.com/kotauskas/interprocess"

description = "Interprocess communication toolkit"
categories = ["os", "os::unix-apis", "os::windows-apis", "asynchronous"]
keywords = ["ipc", "shared_memory", "pipe", "unix_domain_socket"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = { version = "0.2", features = ["extra_traits"] }
tokio = { version = "1.7", features = ["net", "time"], optional = true }
thiserror = { version = "1.0", optional = true }
spinning = { version = "0.1", optional = true }
intmap = { version = "0.7", optional = true }
once_cell = { version = "1.7", optional = true }
blocking = { version = "1.0", optional = true }
futures = { version = "0.3", optional = true }
to_method = "1.1"
cfg-if = "1.0"

[build-dependencies]
rustc_version = "0.4"

[dev-dependencies]
tokio = { version = "1.7", features = ["rt", "macros", "rt-multi-thread"] }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = [
    "std",
    "winbase",
    "winerror",
    "processthreadsapi",
    "fileapi",
    "handleapi",
    "namedpipeapi",
] }

[features]
default = ["signals", "nonblocking", "tokio_support"]
signals = ["thiserror", "spinning", "intmap", "once_cell"]
nonblocking = ["blocking", "futures"]
tokio_support = ["tokio", "futures"]
doc_cfg = []

[package.metadata.docs.rs]
features = ["doc_cfg"]
