name: Checks and tests

on: [push, pull_request]

jobs:
  check_and_test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        toolchain: ["1.75.0", nightly]

    name: ${{ matrix.toolchain }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          profile: minimal
          override: true
          components: clippy

      - name: Run Clippy for default configuration
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: "-- -A unknown_lints"

      - name: Run tests for default configuration
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Run rustdoc for default configuration
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: "--no-deps"

      - name: Run Clippy for Tokio configuration
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: "--features tokio -- -A unknown_lints"

      - name: Run tests for Tokio configuration
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: "--features tokio"

      - name: Run rustdoc for Tokio configuration
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: "--features tokio --no-deps"
