name: Checks and tests

on: [push, pull_request]

jobs:
  check_and_test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        toolchain: ["1.75.0", nightly]

    name: ${{ matrix.toolchain }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      RUSTFLAGS: --cfg ci
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install Rust
        run: |
          rustup toolchain install ${{ matrix.toolchain }} --profile minimal --component clippy
          rustup default ${{ matrix.toolchain }}

      - name: Run Clippy for default configuration
        run: cargo clippy -- -A unknown_lints

      - name: Run tests for default configuration
        run: cargo test

      - name: Run rustdoc for default configuration
        run: cargo doc --no-deps

      - name: Run Clippy for Tokio configuration
        run: cargo clippy --features tokio -- -A unknown_lints

      - name: Run tests for Tokio configuration
        run: cargo test --features tokio

      - name: Run rustdoc for Tokio configuration
        run: cargo doc --features tokio --no-deps
